// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApz15yqXhAo9H0z2qYcsjJgCsqPO7gXYc',
    appId: '1:633594977993:web:515457dc806b45ed73b718',
    messagingSenderId: '633594977993',
    projectId: 'aravision-39e6d',
    authDomain: 'aravision-39e6d.firebaseapp.com',
    storageBucket: 'aravision-39e6d.appspot.com',
    measurementId: 'G-ZGFM37MSZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkm4hqALbbIKGV9UqknUe4SM05ywXBwgw',
    appId: '1:633594977993:android:333b0ed2d7f724df73b718',
    messagingSenderId: '633594977993',
    projectId: 'aravision-39e6d',
    storageBucket: 'aravision-39e6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwrgc8NEtwkg918vzfp8canve18Ed0ahY',
    appId: '1:633594977993:ios:86544ad4faabd5ba73b718',
    messagingSenderId: '633594977993',
    projectId: 'aravision-39e6d',
    storageBucket: 'aravision-39e6d.appspot.com',
    iosBundleId: 'com.example.aravision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwrgc8NEtwkg918vzfp8canve18Ed0ahY',
    appId: '1:633594977993:ios:afb0274f4ef2043873b718',
    messagingSenderId: '633594977993',
    projectId: 'aravision-39e6d',
    storageBucket: 'aravision-39e6d.appspot.com',
    iosBundleId: 'com.example.aravision.RunnerTests',
  );
}
